import {
  Incident,
  IncidentSnapshot,
  EvidenceLink,
  ActionPlan,
  Resource,
  Evidence,
} from '../../types';

export const demoResources: Resource[] = [
  {
    resource_id: 'RES-01',
    name: 'Water Rescue Boat Unit Alpha',
    resource_type: 'rescue_boat',
    location: { lat: 12.9300, lng: 77.6200, address: 'Station 4 Riverfront Dock' },
    availability: 'available',
    capacity: 6,
    estimated_eta_minutes: 12,
  },
  {
    resource_id: 'RES-02',
    name: 'Rapid Medical Emergency Unit 03',
    resource_type: 'ambulance',
    location: { lat: 12.9400, lng: 77.6300, address: 'General Hospital Base Sector 4' },
    availability: 'available',
    capacity: 2,
    estimated_eta_minutes: 8,
  },
  {
    resource_id: 'RES-03',
    name: 'High-Capacity Evacuation Bus 09',
    resource_type: 'evacuation_bus',
    location: { lat: 12.9250, lng: 77.6150, address: 'City Transit Central Depot' },
    availability: 'available',
    capacity: 40,
    estimated_eta_minutes: 20,
  },
];

export const demoSnapshots: IncidentSnapshot[] = [
  {
    snapshot_id: 'SNAP-001',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:02:00Z',
    severity: 'medium',
    people_affected: 0,
    access_status: 'partially_blocked',
    active_needs: [],
    priority_score: 45.0,
    summary: 'Flash flood detected on 4th Main near Central Market Bridge. Water rising over curb.',
    delta_summary: [
      'Initial flood report logged via citizen upload',
      'Water level accumulation on roadway',
      'Access status: PARTIALLY BLOCKED',
    ],
  },
  {
    snapshot_id: 'SNAP-002',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:08:00Z',
    severity: 'high',
    people_affected: 5,
    access_status: 'partially_blocked',
    active_needs: ['rescue'],
    priority_score: 68.0,
    summary: '5 residents trapped inside bakery by rising water (1.2m deep). Immediate boat rescue requested.',
    delta_summary: [
      '+5 people affected (stranded inside bakery)',
      '+New need detected: Water Rescue',
      'Severity escalated to HIGH',
      'Priority score increased to 68.0 / 100',
    ],
  },
  {
    snapshot_id: 'SNAP-003',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:14:00Z',
    severity: 'high',
    people_affected: 5,
    access_status: 'blocked',
    active_needs: ['rescue'],
    priority_score: 75.0,
    summary: 'Police patrol reports east and west approach lanes submerged. Vehicles cannot pass.',
    delta_summary: [
      'Road access changed from partially_blocked to BLOCKED',
      'Standard vehicular ingress impassable',
      'Hazard radius estimated at 250 meters',
    ],
  },
  {
    snapshot_id: 'SNAP-004',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:21:00Z',
    severity: 'critical',
    people_affected: 5,
    access_status: 'blocked',
    active_needs: ['rescue', 'medical'],
    priority_score: 88.5,
    summary: 'Critical 911 update: 68-year-old resident suffering acute asthma & heart palpitations on bakery roof terrace.',
    delta_summary: [
      'CRITICAL: Acute cardiac and asthma emergency on roof terrace',
      '+New critical need detected: Paramedic Medical Assistance',
      'Severity escalated to CRITICAL',
      'Dynamic priority recalculated to 88.5 / 100',
    ],
  },
  {
    snapshot_id: 'SNAP-005',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:25:00Z',
    severity: 'critical',
    people_affected: 5,
    access_status: 'blocked',
    active_needs: ['rescue', 'medical'],
    priority_score: 88.5,
    summary: 'Incident Commander confirmed AI recommendation: Water Rescue Boat Alpha & Paramedic Unit 03 deployed.',
    delta_summary: [
      'Responder verification completed: Recommendation APPROVED',
      'Rescue Boat Alpha & Ambulance 03 assigned to incident',
      'Deployment via northern elevated ramp initiated',
    ],
  },
  {
    snapshot_id: 'SNAP-006',
    incident_id: 'INC-001',
    timestamp: '2026-09-25T10:40:00Z',
    severity: 'medium',
    people_affected: 5,
    access_status: 'partially_blocked',
    active_needs: [],
    priority_score: 35.0,
    summary: 'All 5 individuals safely evacuated to medical triage base. Upstream floodgate closed; water level dropping.',
    delta_summary: [
      'Water level dropped from 1.5m to 0.7m',
      'All 5 civilians confirmed safe and transferred to triage',
      'Needs fulfilled: Rescue and Medical marked MET',
      'Incident transitioned to CONTAINED / RECOVERY phase',
    ],
  },
];

export const demoEvidenceList: EvidenceLink[] = [
  {
    link_id: 'EL-001',
    incident_id: 'INC-001',
    evidence_id: 'EV-001',
    linked_at: '2026-09-25T10:02:15Z',
    similarity_score: 0.96,
    link_rationale: 'Spatial proximity within 50m and keyword match: flash flood',
    evidence: {
      evidence_id: 'EV-001',
      report_id: 'R-001',
      disaster_type: 'flood',
      severity: 'medium',
      people_affected: undefined,
      needs: [],
      access_status: 'partially_blocked',
      location: { lat: 12.9352, lng: 77.6245, address: '4th Main & Central Market Bridge' },
      urgency: 'medium',
      extracted_entities: { water_depth: 'ankle deep', flow: 'moderate' },
      confidence: {
        disaster_type: 0.98,
        severity: 0.85,
        people_affected: 0.50,
        needs: 0.60,
        access_status: 0.88,
        location: 0.95,
        urgency: 0.80,
      },
      raw_report: {
        report_id: 'R-001',
        text: 'Heavy flash flood starting on 4th Main near Central Market Bridge. Water is rising fast over the sidewalk.',
        media: [
          {
            media_id: 'M-001',
            media_type: 'image/jpeg',
            url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80',
            caption: 'Water surging onto sidewalk',
          },
        ],
        source: 'citizen',
        timestamp: '2026-09-25T10:02:00Z',
      },
      extracted_at: '2026-09-25T10:02:10Z',
    },
  },
  {
    link_id: 'EL-002',
    incident_id: 'INC-001',
    evidence_id: 'EV-003',
    linked_at: '2026-09-25T10:08:20Z',
    similarity_score: 0.94,
    link_rationale: 'Spatial match 40m from bridge and temporal proximity: 6 mins',
    evidence: {
      evidence_id: 'EV-003',
      report_id: 'R-003',
      disaster_type: 'flood',
      severity: 'high',
      people_affected: 5,
      needs: ['rescue'],
      access_status: 'blocked',
      location: { lat: 12.9351, lng: 77.6243, address: 'Bakery at Bridge Foot, Sector 4' },
      urgency: 'high',
      extracted_entities: { structure: 'commercial bakery', depth_meters: 1.2 },
      confidence: {
        disaster_type: 0.99,
        severity: 0.92,
        people_affected: 0.95,
        needs: 0.96,
        access_status: 0.90,
        location: 0.97,
        urgency: 0.94,
      },
      raw_report: {
        report_id: 'R-003',
        text: 'Emergency 911 call: Five people are trapped inside the ground floor bakery adjacent to the bridge. Water is 1.2 meters deep and entering through windows. Need immediate boat rescue.',
        media: [],
        source: 'emergency_call',
        timestamp: '2026-09-25T10:08:00Z',
      },
      extracted_at: '2026-09-25T10:08:15Z',
    },
  },
  {
    link_id: 'EL-003',
    incident_id: 'INC-001',
    evidence_id: 'EV-005',
    linked_at: '2026-09-25T10:14:22Z',
    similarity_score: 0.95,
    link_rationale: 'Official police unit on-site traffic observation',
    evidence: {
      evidence_id: 'EV-005',
      report_id: 'R-005',
      disaster_type: 'flood',
      severity: 'high',
      people_affected: 5,
      needs: ['rescue', 'transport'],
      access_status: 'blocked',
      location: { lat: 12.9350, lng: 77.6240, address: 'Central Market West Intersection' },
      urgency: 'high',
      extracted_entities: { road_closure: 'both lanes', vehicle_stranded: 'sedan' },
      confidence: {
        disaster_type: 0.99,
        severity: 0.90,
        people_affected: 0.90,
        needs: 0.85,
        access_status: 0.98,
        location: 0.98,
        urgency: 0.90,
      },
      raw_report: {
        report_id: 'R-005',
        text: 'Patrol Unit 14 on scene: Vehicles cannot pass. Both east and west approach lanes are completely submerged and blocked. Abandoned sedan stranded in middle of junction.',
        media: [],
        source: 'police_patrol',
        timestamp: '2026-09-25T10:14:00Z',
      },
      extracted_at: '2026-09-25T10:14:15Z',
    },
  },
  {
    link_id: 'EL-004',
    incident_id: 'INC-001',
    evidence_id: 'EV-007',
    linked_at: '2026-09-25T10:21:20Z',
    similarity_score: 0.97,
    link_rationale: 'Direct correlation with trapped bakery civilians',
    evidence: {
      evidence_id: 'EV-007',
      report_id: 'R-007',
      disaster_type: 'flood',
      severity: 'critical',
      people_affected: 5,
      needs: ['rescue', 'medical'],
      access_status: 'blocked',
      location: { lat: 12.9351, lng: 77.6243, address: 'Bakery Roof Terrace, Sector 4' },
      urgency: 'critical',
      extracted_entities: { patient_age: 68, condition: 'severe asthma attack & heart palpitations' },
      confidence: {
        disaster_type: 0.99,
        severity: 0.98,
        people_affected: 0.95,
        needs: 0.98,
        access_status: 0.95,
        location: 0.98,
        urgency: 0.99,
      },
      raw_report: {
        report_id: 'R-007',
        text: 'CRITICAL UPDATE: Trapped civilian reports 68-year-old female suffering severe asthma attack and acute heart palpitations on the roof. Medical emergency! Oxygen and paramedic rescue required urgently.',
        media: [],
        source: 'emergency_call',
        timestamp: '2026-09-25T10:21:00Z',
      },
      extracted_at: '2026-09-25T10:21:10Z',
    },
  },
];

export const demoRecommendation: ActionPlan = {
  action_id: 'ACT-001',
  incident_id: 'INC-001',
  priority_level: 'critical',
  priority_score: 88.5,
  priority_rationale: [
    '5 civilians directly trapped with water surrounding ground structure',
    'Road access completely BLOCKED preventing standard wheeled emergency vehicles',
    'Critical medical emergency reported: 68-year-old acute cardiac and asthma distress',
    'Flood current velocity elevated (1.8 m/s) requiring motorized watercraft',
  ],
  recommended_resources: [
    demoResources[0], // Rescue Boat Alpha
    demoResources[1], // Rapid Medical Unit 03
  ],
  resource_rationale:
    'Dispatched Water Rescue Boat Unit Alpha (capacity 6, ETA 12 min) to navigate 1.2m flood water and evacuate 5 roof-bound residents. Dispatched Rapid Medical Unit 03 (paramedics, ETA 8 min) to stage at northern elevated ramp with oxygen and cardiac stabilization equipment.',
  verification_status: 'pending',
  verified_by: undefined,
  verified_at: undefined,
  responder_notes: undefined,
  created_at: '2026-09-25T10:21:30Z',
};

export const demoIncidents: Incident[] = [
  {
    incident_id: 'INC-001',
    title: 'Flash Flood & Bridge Inundation — Sector 4',
    disaster_type: 'flood',
    status: 'active',
    severity: 'critical',
    priority_level: 'critical',
    priority_score: 88.5,
    location: {
      lat: 12.9352,
      lng: 77.6245,
      address: 'Central Market Bridge, Sector 4',
      radius_meters: 250,
    },
    people_affected: 5,
    access_status: 'blocked',
    evidence_links: demoEvidenceList,
    current_impact: {
      impact_id: 'IMP-001',
      casualty_count: 0,
      displaced_count: 5,
      trapped_count: 5,
      infrastructure_damage: {
        bridge_curb: 'submerged (1.2m water)',
        power_grid: 'offline (junction box isolated)',
        approach_roads: 'completely blocked',
      },
      hazard_radius_meters: 250,
      environmental_hazards: ['Fast river current (1.8 m/s)', 'Submerged debris', 'Downed power line'],
      updated_at: '2026-09-25T10:21:30Z',
    },
    current_needs: [
      {
        need_id: 'ND-001',
        type: 'rescue',
        urgency: 'high',
        confidence: 0.96,
        status: 'unmet',
        quantity: 5,
        description: 'Motorized watercraft needed to evacuate 5 trapped rooftop residents',
        identified_at: '2026-09-25T10:08:15Z',
      },
      {
        need_id: 'ND-002',
        type: 'medical',
        urgency: 'critical',
        confidence: 0.98,
        status: 'unmet',
        quantity: 1,
        description: 'Advanced life support / oxygen needed for 68-year-old cardiac distress patient',
        identified_at: '2026-09-25T10:21:10Z',
      },
      {
        need_id: 'ND-003',
        type: 'transport',
        urgency: 'medium',
        confidence: 0.85,
        status: 'unmet',
        quantity: 5,
        description: 'Secondary transit bus required once extracted to northern elevated ramp',
        identified_at: '2026-09-25T10:14:15Z',
      },
    ],
    active_recommendation: demoRecommendation,
    snapshots: demoSnapshots,
    contradictions: [],
    created_at: '2026-09-25T10:02:10Z',
    updated_at: '2026-09-25T10:21:30Z',
  },
  {
    incident_id: 'INC-002',
    title: 'Canal Drainage Overflow — West Industrial Buffer',
    disaster_type: 'flood',
    status: 'active',
    severity: 'medium',
    priority_level: 'medium',
    priority_score: 52.0,
    location: {
      lat: 12.9280,
      lng: 77.6180,
      address: 'Industrial Canal West Gate',
      radius_meters: 100,
    },
    people_affected: 0,
    access_status: 'partially_blocked',
    evidence_links: [],
    current_needs: [
      {
        need_id: 'ND-004',
        type: 'water',
        urgency: 'medium',
        confidence: 0.82,
        status: 'unmet',
        quantity: 1,
        description: 'Submersible water pump needed to prevent warehouse flooding',
        identified_at: '2026-09-25T10:15:00Z',
      },
    ],
    snapshots: [],
    contradictions: [],
    created_at: '2026-09-25T10:15:00Z',
    updated_at: '2026-09-25T10:15:00Z',
  },
];

export const DEMO_INCIDENTS = demoIncidents;
export const DEMO_TIMELINE_SNAPSHOTS = demoSnapshots;
export const DEMO_EVIDENCE: Evidence[] = demoEvidenceList
  .map((l) => l.evidence)
  .filter((e): e is Evidence => Boolean(e));
export const DEMO_RECOMMENDATIONS: ActionPlan[] = [demoRecommendation];
